export const MODULES: any = {
	status: 'Status',
	general: 'General',
	curtain: 'Curtain',
	garland: 'Garland',
	thermostat: 'Thermostat',
	lightfox: 'Lightfox',
	domoticz: 'Domoticz',
	ha: 'Home Assistant',
	idb: 'Influx DB',
	led: 'LED',
	light: 'Light',
	rfm69mapping: 'Mapping',
	rfm69messages: 'Messages',
	mqtt: 'MQTT',
	nofuss: 'No Fuss',
	ntp: 'NTP',
	rfb: 'RF Bridge',
	rpn: 'Rules',
	schedule: 'Schedule',
	sns: 'Sensors',
	relay: 'Relay',
	thingspeak: 'Things Speak',
	wifi: 'Wifi',
	admin: 'Admin',
	cmd: 'Command',
};

export const FOOTER = {};
